### ISSUE TITLE
Is your repro supported on Web?

### ISSUE THREAD

**Issue by linweigao** [netgfx/Shapes-in-the-Dart#2]
Forked and won't be able to run on web.

**Comment by netgfx** [comment]
hm not sure, I haven't tried it. CustomPainter should work without any issues, not sure which part you tried to run as the repo contains multiple subprojects. Also make sure to clone `develop` as `main` is not up to date

**Comment by linweigao** [comment]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building Builder:
Unsupported operation: Platform._operatingSystem

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///Users/ligao/Desktop/code/github/Shapes-in-the-Dart/flutter_shaders/lib/main.dart:23:12

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49     throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                  _operatingSystem
dart-sdk/lib/io/platform_impl.dart 56:40                                         get operatingSystem
dart-sdk/lib/io/platform.dart 64:45                                              get _operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 839:8  get
dart-sdk/lib/io/platform.dart 149:51                                             get isAndroid
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 839:8  get
packages/flutter_shaders/MazeMaker.dart 61:35                                    new
packages/flutter_shaders/MazeMaker.dart 51:36                                    createState

**Comment by netgfx** [comment]
@linweigao the bug is fixed on `develop` and `maze-creator` branches. Have fun!
